# .github/workflows/deploy.yml

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Or your primary branch name (e.g., master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # This is a placeholder, the token below is used
          projectId: 'soccer-hub-f63f5' # Replace with your Firebase Project ID
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # Also a placeholder