name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Replace Gemini API Key
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__GEMINI_API_KEY__"
          replace: "${{ secrets.GEMINI_API_KEY }}"
          include: "index.tsx"

      - name: Replace Paystack Public Key
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__PAYSTACK_PUBLIC_KEY__"
          replace: "${{ secrets.PAYSTACK_PUBLIC_KEY }}"
          include: "index.tsx"
      
      - name: Replace Firebase Config JSON
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "__FIREBASE_CONFIG_JSON__"
          replace: '${{ secrets.FIREBASE_CONFIG_JSON }}'
          include: "index.tsx"

      # This is the corrected deployment step that uses the Service Account
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # This line uses the Service Account key you created to fix the error.
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' 
          # CRITICAL: Make sure to replace this with your actual project ID below
          projectId: 'soccer-hub-f63f5' 